# Generated by Django 3.2.7 on 2021-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJapp', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
