# Generated by Django 3.2.7 on 2021-11-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJapp', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='shop',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
