# Generated by Django 3.2.7 on 2021-11-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJapp', '0004_image_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='pic',
        ),
    ]
